# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gw < Formula
  desc "Git worktree manager with fzf integration"
  homepage "https://github.com/mb6611/gw"
  version "0.2.0"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mb6611/gw/releases/download/v0.2.0/gw_darwin_amd64.tar.gz"
      sha256 "206a476a887bcca7632ac379838c9beb94e0a3884ab3bfdb92255e5e80b21dcb"

      def install
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mb6611/gw/releases/download/v0.2.0/gw_darwin_arm64.tar.gz"
      sha256 "f7221448a6f37e83eb162fee5ec1f9b2ded6ff21f5a13dc0aca78a25e5d73a21"

      def install
        bin.install "gw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mb6611/gw/releases/download/v0.2.0/gw_linux_amd64.tar.gz"
      sha256 "57f911859a656aff70378cad735449f6794db7ce7cc587c37d6a61368277fab7"
      def install
        bin.install "gw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mb6611/gw/releases/download/v0.2.0/gw_linux_arm64.tar.gz"
      sha256 "f46ce9760a4110e38218de6804eb0f880fdffd8b52fd2d760d75fa359fe7933e"
      def install
        bin.install "gw"
      end
    end
  end

  def caveats
    <<~EOS
      Add to your shell config:

        eval "$(gw init zsh)"
    EOS
  end

  test do
    system "#{bin}/gw", "--help"
  end
end
